# Server configuration
server:
  port: 8080
# Hibernate
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres?currentSchema=converter
    username: postgres
    password: root
  flyway:
    baseline-on-migrate: true
    baseline-version: 0
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
    generate-ddl: off
    database: postgresql

webSite.url: https://belarusbank.by/api/kursExchange?city=%D0%93%D0%BE%D0%BC%D0%B5%D0%BB%D1%8C